name: App CI

on:
  push:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"
  pull_request:
    # Run on all branches
    branches:
      - "*"
    # Run only if files modified are not docs
    paths-ignore:
      - "*.md"

jobs:

  # Build & Test
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.22.2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      # Install
      - name: INSTALL
        run: pnpm install

      # Build
      - name: BUILD
        run: pnpm build:ci

      # Test
      - name: TEST
        run: pnpm test:ci

      # Upload dist artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: web-dist
          path: apps/web/dist/

      # Upload coverage artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: web-coverage
          path: apps/web/coverage/lcov.info

  coverage:
    name: Coverage analysis
    needs: buildAndTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Donwload coverage artifacts
      - uses: actions/download-artifact@v2
        with:
          name: web-coverage

      # Update coverage file to codecov
      - name: CODECOV
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
