name: Deploy Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    name: 🐳 Build Web image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🐳 Build docker image
        uses: ./.github/actions/build-docker
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: .
          file: ./apps/web/.docker/Dockerfile
          tags: pchmn/kipzat-web:${{ github.sha }}
          push: true

  deploy-convex:
    name: 🚀 Deploy Convex Preview
    runs-on: ubuntu-latest
    needs: [build-web]
    steps:
      - uses: actions/checkout@v4

      - name: 🏗️ Setup node
        uses: ./.github/actions/setup-node
        with:
          install: true
      
      - name: 🔄 Set environment variables
        working-directory: ./apps/backend
        run: |
          npx convex env set BETTER_AUTH_SECRET ${{ secrets.PREVIEW_BETTER_AUTH_SECRET }}
          npx convex env set GOOGLE_CLIENT_ID ${{ secrets.GOOGLE_CLIENT_ID }}
          npx convex env set GOOGLE_CLIENT_SECRET ${{ secrets.GOOGLE_CLIENT_SECRET }}
          npx convex env set GITHUB_TOKEN ${{ secrets.PAT_GITHUB }}
          npx convex env set VOYAGE_API_KEY ${{ secrets.VOYAGE_API_KEY }}
          npx convex env set GOOGLE_GENERATIVE_AI_API_KEY ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          npx convex env set SITE_URL https://pr-${{ github.event.number }}.preview.kipzat.app
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.PREVIEW_CONVEX_DEPLOY_KEY }}
          # CONVEX_SELF_HOSTED_URL: ${{ secrets.CONVEX_SELF_HOSTED_URL }}
          # CONVEX_SELF_HOSTED_ADMIN_KEY: ${{ secrets.CONVEX_SELF_HOSTED_ADMIN_KEY }}
          
      - name: 🚀 Deploy Functions
        working-directory: ./apps/backend
        run: |
          npx convex deploy
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.PREVIEW_CONVEX_DEPLOY_KEY }}
          # CONVEX_SELF_HOSTED_URL: ${{ secrets.CONVEX_SELF_HOSTED_URL }}
          # CONVEX_SELF_HOSTED_ADMIN_KEY: ${{ secrets.CONVEX_SELF_HOSTED_ADMIN_KEY }}

  deploy-web:
    name: 🚀 Deploy Web App Preview
    runs-on: ubuntu-latest
    needs: [build-web, deploy-convex]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: 🚀 Deploy to Dokploy
        uses: ./.github/actions/dokploy
        with:
          comment-pr: true
          dokploy-base-url: ${{ secrets.DOKPLOY_BASE_URL }}
          dokploy-token: ${{ secrets.DOKPLOY_TOKEN }}
          project-id: 9Q2mI4ygVsQzgTdtlbhjO
          application-name: pr-${{ github.event.number }}
          application-domain: pr-${{ github.event.number }}.preview.kipzat.app
          docker-image: pchmn/kipzat-web:${{ github.sha }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          docker-port: 8080
          env: |
            VITE_APP_VERSION=${{ github.sha }}
            VITE_APP_ENV=preview
            VITE_CONVEX_URL=${{ secrets.PREVIEW_CONVEX_URL }}
            VITE_CONVEX_SITE_URL=${{ secrets.PREVIEW_CONVEX_SITE_URL }}
